### PR TITLE
Pharmacovigilance updates

### PR DESCRIPTION
**Pull request by Itskiprotich**

### CODE REVIEW

**Review by esthermmoturi — CHANGES_REQUESTED** [review]
Hey @Itskiprotich . Here are my comments.Kindly work on the issues:

- [x] Under household the only plus button doesn’t have choices(just an add new person option)

- [x] The hint on the question - Did you notice anything strange with your medicine? Has brackets that are not required

- [ ] On the people summary tab when logged in as CHW, the last visit date is indicated as unknown and displayed in red. Assessment defines the household visit yet it is only submitted for individual household members.

- [ ] Condition card(Assessment summary) is not updated after submitting assessment form - this is to be rechecked after 24 hours

- [ ] Under household condition card, View deceased is available(good work)

- [ ] Yet to be achieved, customized contact forms

**Comment by Itskiprotich** [comment]
@esthermmoturi  thanks for this.

At a glance this is my response:

- Yes at the household level we can only add a household member

- I'm removing the brackets asap
-  We've discussed internally and opted to drop the UHC mode - pushing an update for this
- The condition card is updated when the public report is added, do you advise we factor in responses from the assessment form as well?
- Thanks
- Still working on the contacts forms-  tried the discussed option but I couldn't resolve the missing 'Belongs to'

**Comment by antonykhaemba** [comment]
@Itskiprotich, I would also recommend that you drop the UHC feature and if possible try this [household task feature](https://docs.communityhealthtoolkit.org/apps/features/tasks/#household-tasks). This feature will enable a user be able to access all other household members tasks once they complete a task for one household member. cc @esthermmoturi

**Comment by esthermmoturi** [comment]
Closing this PR to avoid conflicts

**Pull request closed without merging**
