### PR TITLE
Jk pharmacovigilance

### PR DESCRIPTION
**Pull request by Itskiprotich**

### CODE REVIEW

**Comment by esthermmoturi** [comment]
Hey @Itskiprotich , I have reviewed the forms and I would like you to look into the following items:

- The naming for the forms of creating health facility and area have not been named correctly. For example, the first place someone is able to create is a Health Facility, the second area is a Health Center/New person.But when creating the Health Center, it is named as Area and when creating New Area is named as Household
- Once can submit a Public Report as a CHW/Supervisor and under any profile.
- Restrict under which profile(health facility/area), where a new person can be created
- When choosing the county, can you set it for one to be able to input the first letter(to enable pre-fill) since the list of counties in the dropdown is long.
- One is also able to create a Health Facility under a health facility
- Task is still named as "Patient Consultation", probably because you merged main into your branch.
Feel free to reach out if you'd like us to have a quick meeting to explain this further if something is not clear.

**Review by esthermmoturi — CHANGES_REQUESTED** [review]
@Itskiprotich ,I have added comments for your perusal

**Comment by Itskiprotich** [comment]
@esthermmoturi let me work on the above changes

**Comment by Itskiprotich** [comment]
Hey @esthermmoturi, possible we schedule a call?

Hey @Itskiprotich , sure. I am available from 2-3pm, would that work for you?

**Comment by Itskiprotich** [comment]
That's fine @esthermmoturi Thank you.

@Itskiprotich ,alright.Invite sent!

**Review by esthermmoturi — APPROVED** [review]

**Pull request merged**
