### PR TITLE
UPD: enhanced household registration

### PR DESCRIPTION
**Pull request by Itskiprotich**

### CODE REVIEW

**Comment by Itskiprotich** [comment]
Good morning @esthermmoturi,

I'm requesting a brief session on these updates

**Comment by esthermmoturi** [comment]
Hey @Itskiprotich are you available 10-11 am(EAT) today?

**Comment by Itskiprotich** [comment]
@esthermmoturi, Sure that works. Kindly share an invite.

**Comment by esthermmoturi** [comment]
Hey @Itskiprotich , is this the code on the test instance?

**Review by esthermmoturi — APPROVED** [review]
Approved for reference app documentation purpose. I intend to follow up later.

**Pull request merged**
