### PR TITLE
Malaria usecase updated

### PR DESCRIPTION
**Pull request by brian-gacheru**

### CODE REVIEW

**Comment by esthermmoturi** [comment]
Hi @brian-gacheru ,I have reviewed the updates you pushed and have some feedback on the hierarchy and form availability:

1. The household assessment form has one extra row that has nothing(row 42), you might consider removing it
2. One is able to create a supervisor region while logged in as a supervisor
3. Household assessment form is available under all profiles(which profile should this be accessible from)
4. There is some misalignment in the dropdown list of sub-counties 
5. It would also be helpful to pre-fill letters to make it easy to go though the list of counties as explained [here](https://forum.communityhealthtoolkit.org/t/preselection-from-a-long-list-of-choices/2840)
6. There is no title for users created under Supervisor region
7. One is able to create a Supervisor Region under a supervisor profile
8. Is there a reason one should be able to create a supervisor? How do you configure permissions and roles(username/password)
9. Under the Create Community health area form, there is a 'other notes' section that is mandatory.What is the purpose?

I have also observed a couple of other issues in regards to hierarchy, is it possible for us to set up a call to walk through this?

**Review by esthermmoturi — CHANGES_REQUESTED** [review]
I have added comments for your perusal.

**Comment by brian-gacheru** [comment]
> Hi @brian-gacheru ,I have reviewed the updates you pushed and have some feedback on the hierarchy and form availability:
> 
> 1. The household assessment form has one extra row that has nothing(row 42), you might consider removing it
> 2. One is able to create a supervisor region while logged in as a supervisor
> 3. Household assessment form is available under all profiles(which profile should this be accessible from)
> 4. There is some misalignment in the dropdown list of sub-counties
> 5. It would also be helpful to pre-fill letters to make it easy to go though the list of counties as explained [here](https://forum.communityhealthtoolkit.org/t/preselection-from-a-long-list-of-choices/2840)
> 6. There is no title for users created under Supervisor region
> 7. One is able to create a Supervisor Region under a supervisor profile
> 8. Is there a reason one should be able to create a supervisor? How do you configure permissions and roles(username/password)
> 9. Under the Create Community health area form, there is a 'other notes' section that is mandatory.What is the purpose?
> 
> I have also observed a couple of other issues in regards to hierarchy, is it possible for us to set up a call to walk through this?

Thanks for the feedback! We can set up a call tomorrow morning to go through the other issues you have noticed.
@brian-gacheru are you available from 3-4pm today? I can send an invite for then.

**Comment by brian-gacheru** [comment]
I have actioned the comments above and updated the PR with icons and translations as well as forms and tasks @esthermmoturi

**Review by esthermmoturi — CHANGES_REQUESTED** [review]
Hey @brian-gacheru ,kindly action on the items highlighted on the PR.

**Comment by esthermmoturi** [comment]
Hey @brian-gacheru ,some of the issues below have not yet been addressed from last review.I will add them as a checklist so kindly tick them off once you have fixed the issue.

- [x] When a health facility/supervisor region is created and named manually, it appears as a blank.
- [x] Correct the import statement for getField in the contact-summary-templated file. 
- [x] What user role is assigned to a facility nurse created as the primary contact when health facility is created? **No role is assigned automatically. To assign the role a user would have to use the admin app console.**
- [x] How many supervisor regions can be created under a health facility? **Currently there is no limit to how many regions can be created.**
- [x] Primary contact created under Supervisor region/Community Health Area are not placed/assigned as supervisors/chvs. This assignment can also not be done in admin app management user console
- [x] Household assessment form is available to individual contacts and not necessarily households.
- [x] Child under 5 form is available to adults when logged in as adults
- [x] Preselection for the long list is not implemented for household registration form
- [x] No hints put in notes
- [x] Supervisor should not be able to create a household. Clarify this. **Currently a supervisor is able to create a household on behalf of a CHV since a supervisor is higher up in the heirachy.**
- [x] Some parts of creating households is pre-selected. Is this intentional? **No it isn't I have removed the preselected items**
- [x] What is the intention of note ' Please submit monthly screening.....'?
- [x] Household naming is not set to ensure 'Primary Contact's Household'
- [x] Primary contact for household doesn't appear under list of household members Still haven't figured out why it is not showing. Assistance would be appreciated.
- [x] Should other forms other than the muted form be available for a muted contact?Clarify **No. The only form that should be available for a muted contact is the unmute form**
- [x] Once household assessment form has been submitted, selecting a household shows 'No person selected'
- [x] Once household assessment form has been submitted for a close-by date task, task appears but shows 'Error loading form..'

Kindly review these items before we are able to look at other items.

**Comment by brian-gacheru** [comment]
> Hey @brian-gacheru ,some of the issues below have not yet been addressed from last review.I will add them as a checklist so kindly tick them off once you have fixed the issue.
> 
> * [ ]  When a health facility/supervisor region is created and named manually, it appears as a blank.
> * [ ]  Correct the import statement for getField in the contact-summary-templated file.
> * [ ]  What user role is assigned to a facility nurse created as the primary contact when health facility is created?
> * [ ]  How many supervisor regions can be created under a health facility?
> * [ ]  Primary contact created under Supervisor region/Community Health Area are not placed/assigned as supervisors/chvs. This assignment can also not be done in admin app management user console
> * [ ]  Household assessment form is available to individual contacts and not necessarily households.
> * [ ]  Child under 5 form is available to adults when logged in as adults
> * [ ]  Preselection for the long list is not implemented for household registration form
> * [ ]  No hints put in notes
> * [ ]  Supervisor should not be able to create a household. Clarify this.
> * [ ]  Some parts of creating households is pre-selected. Is this intentional?
> * [ ]  What is the intention of note ' Please submit monthly screening.....'?
> * [ ]  Household naming is not set to ensure 'Primary Contact's Household'
> * [ ]  Primary contact for household doesn't appear under list of household members
> * [ ]  Should other forms other than the muted form be available for a muted contact?Clarify
> * [ ]  Once household assessment form has been submitted, selecting a household shows 'No person selected'
> * [ ]  Once household assessment form has been submitted for a close-by date task, task appears but shows 'Error loading form..'
> 
> Kindly review these items before we are able to look at other items.

Thanks for your review. We will work on these items and update.

**Comment by brian-gacheru** [comment]
@esthermmoturi I have updated the code and actioned highlighted items. Kindly review.

**Comment by esthermmoturi** [comment]
Hey @brian-gacheru ,I have reviewed the recent changes and observed that some things have changed but other have not.Kindly address the following issues:

- [x] Fix getField variable in 'contact-summary-templated.js' file.There is no 'cht-nootils' file that the variable is being imported from **This is being imported from a dependency**
- [x] While naming a health facility manually for example 'Westlands', shouldn't it rename and pick up Health facility eg 'Westlands Health Facility'
- [x] Should the community health area code be restricted to a specific type.What is the idea? **The purpose of the code is to act as an identifier if there are areas with the same name. The type is not restricted and can be alphanumeric**
- [x] For the + button under CHW area, place 'Create Household',it shouldn't be blank. **Kindly clarify what you mean by this**
- [ ] Kindly clarify the need of location under household information.The search bar doesn't work. - **The medic team is working to clarify this**
- [x] There are preselected items for 'Create Household form'
- [x] There is a note 'Please submit monthly screening form household member' after registering a household member.
- [x] Fix hint 'Remove this child by pressing the - button' which is shown after registering an adult household member.
- [x] The primary contact is is still not listed under household members.
- [ ] Where household members are listed, there is also a label 'Tasks' **This is how the UI is structured by default. Kindly clarify if I have misunderstood your question**

**Comment by brian-gacheru** [comment]
@esthermmoturi I have actioned the comments you added. Kindly review.

**Comment by esthermmoturi** [comment]
Hey @brian-gacheru ,I am approving this PR and merging to main.Good job on fixing all issues indicated.I will share my observations from my final review and you'll work on them and raise another PR. Thanks.

**Review by esthermmoturi — APPROVED** [review]

**Pull request merged**
